spring:
  datasource:
    url: jdbc:mysql://localhost/chen?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 456718293
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapper-locations:
  - mapper/*.xml